task_manager/labels/urls.py
from django.urls import path

from . import views

app_name = 'labels'

urlpatterns = [
    path('', views.LabelListView.as_view(), name='index'),
    path('create/', views.LabelCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.LabelUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.LabelDeleteView.as_view(), name='delete'),
]

task_manager/tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.TaskListView.as_view(), name='index'),
    path('create/', views.TaskCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.TaskUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.TaskDeleteView.as_view(), name='delete'),
    path('<int:pk>/', views.TaskShowView.as_view(), name='show'),
]

task_manager/urls.py
from django.contrib import admin
from django.urls import include, path

from task_manager import views
from task_manager.users.views import UserLoginView, UserLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.MainPageView.as_view(), name='index'),
    path('users/', include('task_manager.users.urls')),
    path('statuses/', include('task_manager.statuses.urls')),
    path('tasks/', include('task_manager.tasks.urls')),
    path('labels/', include('task_manager.labels.urls')),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

task_manager/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('', views.UserListView.as_view(), name='index'),
    path('create/', views.UserCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.UserUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.UserDeleteView.as_view(), name='delete'),
]

task_manager/labels/models.py
from django.db import models


class Label(models.Model):
    name = models.CharField(
        max_length=256,
        unique=True,
        verbose_name="Имя",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        verbose_name="Дата создания",
    )

    def __str__(self):
        return self.name

task_manager/statuses/models.py
from django.db import models


class Status(models.Model):
    name = models.CharField(
        max_length=256, 
        unique=True, 
        blank=False,
        verbose_name='Имя',
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

task_manager/tasks/models.py
from django.contrib.auth import get_user_model
from django.db import models

from task_manager.labels.models import Label
from task_manager.statuses.models import Status

User = get_user_model()


class Task(models.Model):
    name = models.CharField(max_length=256, verbose_name="Имя")
    description = models.TextField(blank=True, verbose_name="Описание")
    status = models.ForeignKey(
        Status,
        on_delete=models.PROTECT,
        verbose_name='Статус',
        related_name='tasks',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='Автор',
        related_name="tasks_author",
    )
    executor = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        verbose_name='Исполнитель',
        related_name="tasks_executor",
        blank=True,
        null=True,
    )
    labels = models.ManyToManyField(
        Label,
        related_name='tasks',
        blank=True,
        verbose_name='Метки',
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        )

    def __str__(self):
        return self.name

task_manager/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    first_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name='Имя'
    )
    last_name = models.CharField(
        max_length=256,
        blank=False,
        verbose_name='Фамилия'
    )
    USERNAME_FIELD = 'username'

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

task_manager/labels/forms.py
from django import forms

from .models import Label


class LabelForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Label
        fields = ['name']

task_manager/statuses/forms.py
from django import forms

from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = ['name']

task_manager/tasks/forms.py
from django import forms

from .models import Task


class TaskForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Task
        fields = ['name', 'description', 'status', 'executor']

task_manager/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

User = get_user_model()


class UserCreateForm(UserCreationForm):
    password1 = forms.CharField(
        required=True,
        label="Пароль",
        widget=forms.PasswordInput,
        help_text="Ваш пароль должен содержать как минимум 3 символа."
    )
    password2 = forms.CharField(
        required=True,
        label="Подтверждение пароля",
        widget=forms.PasswordInput,
        help_text="Для подтверждения введите, пожалуйста, пароль ещё раз."
    )
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'username',
            'password1',
            'password2'
        ]
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'username': 'Имя пользователя',
        }
        widgets = {
            'first_name': forms.TextInput(attrs={'required': True}),
            'last_name': forms.TextInput(attrs={'required': True}),
            'username': forms.TextInput(attrs={'required': True}),
        }
        help_texts = {
            'username': 'Обязательное поле. Не более 150 символов.\
                  Только буквы, цифры и символы @/./+/-/_.',
        }

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password2:
            if password1 != password2:
                self.add_error("password2", "Введенные пароли не совпадают.")

            if len(password1) < 3:
                self.add_error(
                    "password2",
                    "Введённый пароль слишком короткий. Он \
                        должен содержать как минимум 3 символа.",
                )
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password1")
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user
        

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя',
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class UserUpdateForm(UserCreateForm):
    def clean_username(self):
        username = self.cleaned_data.get('username')

        if username == self.instance.username:
            return username

        if User.objects.filter(username=username).exclude(
            pk=self.instance.pk).exists():
            raise forms.ValidationError(
                User._meta.get_field('username').error_messages['unique']
            )

        return username

task_manager/labels/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from task_manager.views import AuthRequired

from .forms import LabelForm
from .models import Label


class LabelListView(AuthRequired, ListView):
    model = Label
    template_name = 'labels/index.html'
    context_object_name = 'labels'


class LabelCreateView(AuthRequired, SuccessMessageMixin, CreateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/create.html'
    success_url = reverse_lazy('labels:index')
    success_message = "Метка успешно создана"


class LabelUpdateView(AuthRequired, SuccessMessageMixin, UpdateView):
    model = Label
    form_class = LabelForm
    template_name = 'labels/update.html'
    success_url = reverse_lazy('labels:index')
    success_message = "Метка успешно изменена"


class LabelDeleteView(AuthRequired, DeleteView):
    model = Label
    template_name = 'labels/delete.html'
    success_url = reverse_lazy('labels:index')
    success_message = "Метка успешно удалена"
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        
        if self.object.tasks.exists():
            messages.error(
                request,
                "Невозможно удалить метку, потому что она используется"
            )
            return redirect(self.success_url)
            
        response = super().post(request, *args, **kwargs)
        messages.success(self.request, self.success_message)
        return response

task_manager/statuses/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.views import AuthRequired

from .forms import StatusForm
from .models import Status


class StatusCreateView(
    AuthRequired,
    SuccessMessageMixin,
    CreateView,
    ):
    form_class = StatusForm
    template_name = 'statuses/create.html'
    success_url = reverse_lazy('statuses:index')
    success_message = 'Статус успешно создан'


class StatusUpdateView(
    AuthRequired,
    SuccessMessageMixin,
    UpdateView,
    ):
    model = Status
    form_class = StatusForm
    template_name = 'statuses/update.html'
    success_message = 'Статус успешно изменен'
    success_url = reverse_lazy('statuses:index')


class StatusDeleteView(
    AuthRequired,
    SuccessMessageMixin,
    DeleteView,
    ):
    model = Status
    template_name = 'statuses/delete.html'
    success_message = 'Статус успешно удален'
    success_url = reverse_lazy('statuses:index')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        
        if self.object.tasks.exists():
            messages.error(
                request,
                "Невозможно удалить статус, потому что он используется"
            )
            return redirect(self.success_url)
            
        response = super().post(request, *args, **kwargs)
        return response


class StatusListView(
    AuthRequired,
    ListView,
    ):
    model = Status
    template_name = 'statuses/index.html'
    context_object_name = 'statuses'

task_manager/tasks/views.py
from django.contrib import messages
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from task_manager.views import AuthRequired

from .filters import TaskFilter
from .forms import TaskForm
from .models import Task


class TaskListView(AuthRequired, ListView):
    model = Task
    template_name = 'tasks/index.html'
    context_object_name = 'tasks'
    
    def get_queryset(self):
        queryset = Task.objects.all()
        self.filterset = TaskFilter(self.request.GET, queryset=queryset)

        queryset = self.filterset.qs

        if self.request.GET.get('self_tasks'):
            queryset = queryset.filter(author=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = self.filterset
        return context


class TaskShowView(AuthRequired, DetailView):
    model = Task
    template_name = 'tasks/show.html'
    context_object_name = 'task'


class TaskCreateView(AuthRequired, SuccessMessageMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/create.html'
    success_url = reverse_lazy('tasks:index')
    success_message = "Задача успешно создана"

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TaskUpdateView(AuthRequired, SuccessMessageMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/update.html'
    success_url = reverse_lazy('tasks:index')
    success_message = "Задача успешно изменена"


class TaskDeleteView(AuthRequired, SuccessMessageMixin,
                     UserPassesTestMixin, DeleteView):
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:index')
    success_message = "Задача успешно удалена"

    def test_func(self):
        task = self.get_object()
        return task.author == self.request.user

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return super().handle_no_permission()
        messages.error(self.request, "Задачу может удалить только ее автор")
        return redirect(self.success_url)

task_manager/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    ListView,
    UpdateView,
)

from task_manager.views import AuthRequired

from .forms import UserCreateForm, UserLoginForm, UserUpdateForm

User = get_user_model()


class UserCreateView(
    SuccessMessageMixin,
    CreateView,
    ):
    form_class = UserCreateForm
    template_name = 'users/create.html'
    success_url = reverse_lazy('login')
    success_message = 'Пользователь успешно зарегистрирован'


class UserPermission(
    AuthRequired,
    UserPassesTestMixin,
    SuccessMessageMixin,
    ):
    model = User
    success_url = reverse_lazy('users:index')

    def test_func(self):
        return self.request.user == self.get_object()

    def handle_no_permission(self):
        if not self.request.user.is_authenticated:
            return super().handle_no_permission()
        messages.error(self.request, 'У вас нет прав для изменения')
        return redirect('users:index')


class UserUpdateView(
    UserPermission,
    UpdateView,
    ):
    form_class = UserUpdateForm
    template_name = 'users/update.html'
    success_message = 'Пользователь успешно изменен'


class UserDeleteView(
    UserPermission,
    DeleteView,
    ):
    template_name = 'users/delete.html'
    success_message = 'Пользователь успешно удален'

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        
        if self.object.tasks_executor.exists() or \
            self.object.tasks_author.exists():
            messages.error(
                request,
                "Невозможно удалить поьзователя, потому что он используется"
            )
            return redirect(self.success_url)
            
        response = super().post(request, *args, **kwargs)
        return response


class UserListView(ListView):
    model = User
    template_name = 'users/index.html'
    context_object_name = 'users'


class UserLoginView(SuccessMessageMixin, LoginView):
    template_name = 'users/login.html'
    form_class = UserLoginForm
    success_message = 'Вы залогинены'
    
    def get_success_url(self):
        return reverse_lazy('index')
    

class UserLogoutView(LogoutView):
    next_page = reverse_lazy('index')

    def dispatch(self, request, *args, **kwargs):
        messages.info(request, 'Вы разлогинены')
        return super().dispatch(request, *args, **kwargs)

task_manager/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.views.generic import TemplateView


class MainPageView(TemplateView):
    template_name = "index.html"


class AuthRequired(LoginRequiredMixin):

    def handle_no_permission(self):
        messages.error(self.request, 'Вы не авторизованы! \
                       Пожалуйста, выполните вход.')
        return redirect('login')

task_manager/templates/tasks/create.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}
Создать задачу
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Создать" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}

task_manager/templates/tasks/delete.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}
Удаление задачи
{% endblock %}

{% block content %}   
<p>Вы уверены, что хотите удалить {{ task.name }}?</p>
<form method="post">
    {% csrf_token %}
    {% bootstrap_button "Да, удалить" button_type="submit" button_class="btn-danger" %}
</form>
{% endblock %}

task_manager/templates/tasks/index.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}
Задачи
{% endblock %}

{% block content %}
<a class="btn btn-primary mb-3" href="{% url 'tasks:create' %}" role="button">Создать задачу</a>
<div class="card mb-3">
    <div class="card-body bg-light">
<form method="get" class="form-inline center">
    {% bootstrap_field filter.form.status show_label=True %}
    {% bootstrap_field filter.form.executor show_label=True %}
    {% bootstrap_field filter.form.labels show_label=True %}

    <div class="form-group mb-3">
        <div class="form-check">
            <input type="checkbox"
                    name="self_tasks"
                    id="id_self_tasks"
                    class="form-check-input"
                    {% if request.GET.self_tasks %}checked{% endif %}>
            <label class="form-check-label" for="id_self_tasks">
                Только свои задачи
            </label>
        </div>
    </div>

    <button type="submit" class="btn btn-primary">Показать</button>
</form>
    </div></div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Имя</th>
            <th>Статус</th>
            <th>Автор</th>
            <th>Исполнитель</th>
            <th>Дата создания</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.id }}</td>
            <td>
                <a href="{% url 'tasks:show' task.id %}">{{ task.name }}</a>
            </td>
            <td>{{ task.status.name }}</td>
            <td>{{ task.author.get_full_name }}</td>
            <td>{% if task.executor %}
                {{ task.executor.get_full_name }}
            {% endif %}</td>
            <td>{{ task.created_at|date:"d.m.Y H:i" }}</td>
            <td>
                <a href="{% url 'tasks:update' task.id %}">Изменить</a>
                <br>
                <a href="{% url 'tasks:delete' task.id %}">Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

task_manager/templates/tasks/show.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}
Просмотр задачи
{% endblock %}

{% block content %}
    <div class="card">
      <div class="card-header bg-secondary text-white">
        <h2>{{ task.name }}</h2>
      </div>
      <div class="card-body bg-light">
        <p>{{ task.description }}</p>
        <hr>
        <div class="container">
          <div class="row p-1">
            <div class="col">Автор</div>
            <div class="col">{{ task.author.get_full_name|default:task.author.username }}</div>
          </div>
          <div class="row p-1">
            <div class="col">Исполнитель</div>
            <div class="col">{% if task.executor %}
                {{ task.executor.get_full_name|default:task.executor.username }}
            {% else %}
                None
            {% endif %}</div>
          </div>
          <div class="row p-1">
            <div class="col">Статус</div>
            <div class="col">{{ task.status.name }}</div>
          </div>
          <div class="row p-1">
            <div class="col">Дата создания</div>
            <div class="col">{{ task.created_at|date:"d.m.Y H:i" }}</div>
          </div>
          <div class="row p-1">
            <div class="col">
              <h6>Метки:</h6>
              <ul>
                {% if task.labels.all %}
                            {% for label in task.labels.all %}
                            <li>{{ label.name }}</li>
                            {% endfor %}
                        {% endif %}
              </ul>
            </div>
          </div>
          <div class="row p-1">
            <div class="col">
              <a href="{% url 'tasks:update' task.id %}">Изменить</a>
              <br>
              <a href="{% url 'tasks:delete' task.id %}">Удалить</a>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

task_manager/templates/tasks/update.html
{% extends "layout.html" %}
{% load django_bootstrap5 %}

{% block title %}
Изменение задачи
{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    {% bootstrap_button "Изменить" button_type="submit" button_class="btn-primary" %}
</form>
{% endblock %}